export const EXERCISE_DB = [
  // ── CHEST ──────────────────────────────────────
  { name: "Bench Press (Barbell)", muscle: "Chest" },
  { name: "Bench Press (Dumbbell)", muscle: "Chest" },
  { name: "Incline Bench Press (Barbell)", muscle: "Chest" },
  { name: "Incline Bench Press (Dumbbell)", muscle: "Chest" },
  { name: "Decline Bench Press", muscle: "Chest" },
  { name: "Chest Fly (Machine)", muscle: "Chest" },
  { name: "Chest Fly (Dumbbell)", muscle: "Chest" },
  { name: "Cable Crossover", muscle: "Chest" },
  { name: "Push-ups", muscle: "Chest" },
  { name: "Dips (Chest)", muscle: "Chest" },
  { name: "Pec Deck", muscle: "Chest" },
  { name: "Landmine Press", muscle: "Chest" },

  // ── BACK ───────────────────────────────────────
  { name: "Deadlift", muscle: "Back" },
  { name: "Romanian Deadlift", muscle: "Back" },
  { name: "Pull-ups", muscle: "Back" },
  { name: "Chin-ups", muscle: "Back" },
  { name: "Lat Pulldown", muscle: "Back" },
  { name: "Seated Cable Row", muscle: "Back" },
  { name: "Bent Over Row (Barbell)", muscle: "Back" },
  { name: "Bent Over Row (Dumbbell)", muscle: "Back" },
  { name: "Single Arm Row (Dumbbell)", muscle: "Back" },
  { name: "T-Bar Row", muscle: "Back" },
  { name: "Meadows Row", muscle: "Back" },
  { name: "Cable Straight Arm Pulldown", muscle: "Back" },
  { name: "Hyperextensions", muscle: "Back" },
  { name: "Rack Pull", muscle: "Back" },

  // ── SHOULDERS ─────────────────────────────────
  { name: "Overhead Press (Barbell)", muscle: "Shoulders" },
  { name: "Overhead Press (Dumbbell)", muscle: "Shoulders" },
  { name: "Lateral Raises", muscle: "Shoulders" },
  { name: "Front Raises", muscle: "Shoulders" },
  { name: "Rear Delt Fly", muscle: "Shoulders" },
  { name: "Arnold Press", muscle: "Shoulders" },
  { name: "Face Pulls", muscle: "Shoulders" },
  { name: "Upright Row", muscle: "Shoulders" },
  { name: "Cable Lateral Raise", muscle: "Shoulders" },
  { name: "Seated Dumbbell Press", muscle: "Shoulders" },

  // ── LEGS ──────────────────────────────────────
  { name: "Squat (Barbell)", muscle: "Legs" },
  { name: "Front Squat", muscle: "Legs" },
  { name: "Leg Press", muscle: "Legs" },
  { name: "Hack Squat", muscle: "Legs" },
  { name: "Leg Extension", muscle: "Legs" },
  { name: "Hamstring Curl (Seated)", muscle: "Legs" },
  { name: "Hamstring Curl (Lying)", muscle: "Legs" },
  { name: "Lunges", muscle: "Legs" },
  { name: "Walking Lunges", muscle: "Legs" },
  { name: "Bulgarian Split Squat", muscle: "Legs" },
  { name: "Goblet Squat", muscle: "Legs" },
  { name: "Calf Raises (Standing)", muscle: "Legs" },
  { name: "Calf Raises (Seated)", muscle: "Legs" },
  { name: "Hip Thrust", muscle: "Legs" },
  { name: "Glute Bridge", muscle: "Legs" },
  { name: "Sumo Deadlift", muscle: "Legs" },
  { name: "Step-ups", muscle: "Legs" },
  { name: "Box Jumps", muscle: "Legs" },

  // ── ARMS ──────────────────────────────────────
  { name: "Bicep Curl (Barbell)", muscle: "Arms" },
  { name: "Bicep Curl (Dumbbell)", muscle: "Arms" },
  { name: "Hammer Curl", muscle: "Arms" },
  { name: "Preacher Curl", muscle: "Arms" },
  { name: "Incline Dumbbell Curl", muscle: "Arms" },
  { name: "Cable Bicep Curl", muscle: "Arms" },
  { name: "Concentration Curl", muscle: "Arms" },
  { name: "Tricep Pushdown", muscle: "Arms" },
  { name: "Tricep Rope Pushdown", muscle: "Arms" },
  { name: "Skullcrushers", muscle: "Arms" },
  { name: "Tricep Dips", muscle: "Arms" },
  { name: "Overhead Tricep Extension", muscle: "Arms" },
  { name: "Close Grip Bench Press", muscle: "Arms" },
  { name: "Diamond Push-ups", muscle: "Arms" },
  { name: "Wrist Curls", muscle: "Arms" },

  // ── CORE ──────────────────────────────────────
  { name: "Crunches", muscle: "Core" },
  { name: "Plank", muscle: "Core" },
  { name: "Leg Raises", muscle: "Core" },
  { name: "Hanging Leg Raises", muscle: "Core" },
  { name: "Russian Twists", muscle: "Core" },
  { name: "Cable Crunch", muscle: "Core" },
  { name: "Ab Wheel Rollout", muscle: "Core" },
  { name: "Bicycle Crunches", muscle: "Core" },
  { name: "Hollow Body Hold", muscle: "Core" },
  { name: "Side Plank", muscle: "Core" },
  { name: "Dragon Flag", muscle: "Core" },
  { name: "Pallof Press", muscle: "Core" },

  // ── CARDIO ────────────────────────────────────
  { name: "Treadmill Run", muscle: "Cardio" },
  { name: "Incline Walk", muscle: "Cardio" },
  { name: "Cycling", muscle: "Cardio" },
  { name: "Elliptical", muscle: "Cardio" },
  { name: "Rowing Machine", muscle: "Cardio" },
  { name: "Jump Rope", muscle: "Cardio" },
  { name: "Stair Climber", muscle: "Cardio" },
  { name: "Battle Ropes", muscle: "Cardio" },
  { name: "Burpees", muscle: "Cardio" },
  { name: "HIIT Sprint", muscle: "Cardio" },
];
